### PR TITLE
ci: build avahi on aarch64, i386, ppc64le, s390x, x86_64 on PRs

### PR DESCRIPTION
**Pull request by evverx**
It already works:
https://github.com/evverx/avahi/pull/3/checks?check_run_id=19440388533
https://copr.fedorainfracloud.org/coprs/packit/evverx-avahi-3/builds/

Depends on https://github.com/avahi/avahi/issues/540

### CODE REVIEW

**Review by pemensik — APPROVED** [review]
This seems nice. Do we have any avahi COPR repository already, where this can be tried?

**Comment by pemensik** [comment]
From my team I am working in, only tuned [uses packit](https://github.com/redhat-performance/tuned/blob/master/.packit.yaml) in their upstream project. I were asked, why we do not use ``fedora-all`` in our proposal. Is there a specific reason for it?

**Comment by evverx** [comment]
> Do we have any avahi COPR repository already, where this can be tried?

It's built at https://copr.fedorainfracloud.org/coprs/packit/evverx-avahi-3/ regularly but the avahi repository itself hasn't been hooked up yet.

> why we do not use fedora-all in our proposal. Is there a specific reason for it?

rawhide is kind of unstable (for example today one build failed on rawhide-i386: https://copr.fedorainfracloud.org/coprs/packit/evverx-avahi-3/build/6946551/) so it's easier to temporarily turn it off by commenting it out if it's mentioned explicitly. `fedora-all` should work too though.

**Comment by evverx** [comment]
I'll go ahead and merge it to make it easier for me to run those builds using my fork at least. Currently I have to cherry-pick this commit on top of PRs every time. It should still be hooked up but it's tracked in a separate issue. It still builds fine: https://copr.fedorainfracloud.org/coprs/packit/evverx-avahi-3/build/7018789/

**Pull request merged**
