### PR TITLE
Testing style checker in SAST scans

### PR DESCRIPTION
**Pull request by siteshwar**
This is a pull request to test style checker in SAST scans. It should not be merged.

### CODE REVIEW

**Comment by siteshwar** [comment]
Test was successful. The reverted commit shows up as a new finding in https://openscanhub.fedoraproject.org/task/9999/log/added.html

**Comment by siteshwar** [comment]
I am closing this pull request, but upstream maintainers may want to cherry pick https://github.com/avahi/avahi/pull/641/commits/912a983b27a9f016cb0b24c9ef4b4defa1e05da7.

CC @evverx

**Comment by evverx** [comment]
Thanks! I'll reopen it and add the "dont-merge" and "CI" labels so as not to forget about this.

**Comment by evverx** [comment]
Looks like I can't update this PR with my fine-grained token (because it can't have access to the fork). Instead of generating new tokens I opened https://github.com/avahi/avahi/pull/642 where I cherry-picked the second commit. I'll merge it once the CI is green. Thanks again!

**Pull request closed without merging**
