### PR TITLE
Added dns_sd feature to support the more coming flag.

### PR DESCRIPTION
**Pull request by tpenguin**
- Added dns_sd feature to support the kDNSServiceFlagsMoreComing
  flag to service_browser_callback(), domain_browser_callback(),
  and query_resolver_callback().

### CODE REVIEW

**Comment by garethsb** [comment]
Were there problems with this PR that prevented it being accepted?

**Comment by davidjsherman** [comment]
I can't speak to any broader issues, but for anecdotal evidence we successfully used the patch from this PR for two years at least to improve compatibility on Linux; at the time [we had out of order problems because Avahi did not set `kDNSServiceFlagsMoreComing`](https://github.com/aseba-community/aseba/pull/556#issuecomment-248728850).

**Comment by pemensik** [comment]
This is quite old change. It is still revelant to latest master?

**Comment by jbenden** [comment]
It should be...

**Comment by fwcd** [comment]
+1, would be really awesome to have this.

My use case is the [`swift-dns-service-discovery`](https://github.com/fwcd/swift-dns-service-discovery) library, which uses the compat layer e.g. to browse for a list of instances of a service. Since the API uses a callback that is called once per instance, the consumer needs some way of determining "when to stop" adding instances to their list. The `.moreComing` flag precisely models this, without the need to resort to unsafe/racy workarounds such as timeouts.

For reference, this seems to be the main blocker for https://github.com/fwcd/swift-dns-service-discovery/pull/7.

**Comment by evverx** [comment]
I rebased this PR on top of the master branch of my fork to trigger the CI. Looks like it fails to compile with
```
cc -DHAVE_CONFIG_H -I. -I..    -I.. '-DDEBUG_TRAP=__asm__("int $3")'  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -std=c99 -Wall -W -Wextra -pedantic -pipe -Wformat -Wold-style-definition -Wdeclaration-after-statement -Wfloat-equal -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -fdiagnostics-show-option -Wno-cast-qual -fno-strict-aliasing -c -o null_test-compat.o `test -f 'compat.c' || echo './'`compat.c
compat.c: In function â€˜service_browser_callbackâ€™:
compat.c:605:40: error: implicit declaration of function â€˜callocâ€™ [-Werror=implicit-function-declaration]
  605 |                 browse_list_t *entry = calloc(1, sizeof(browse_list_t));
      |                                        ^~~~~~
compat.c:50:1: note: include â€˜<stdlib.h>â€™ or provide a declaration of â€˜callocâ€™
   49 | #include "dns_sd.h"
  +++ |+#include <stdlib.h>
   50 | 
compat.c:605:40: warning: incompatible implicit declaration of built-in function â€˜callocâ€™ [-Wbuiltin-declaration-mismatch]
  605 |                 browse_list_t *entry = calloc(1, sizeof(browse_list_t));
      |                                        ^~~~~~
compat.c:605:40: note: include â€˜<stdlib.h>â€™ or provide a declaration of â€˜callocâ€™
compat.c:651:17: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  651 |                 browse_list_t *tmp = entry->list_next;
      |                 ^~~~~~~~~~~~~
compat.c:652:17: error: implicit declaration of function â€˜freeâ€™ [-Werror=implicit-function-declaration]
  652 |                 free(entry->name);
      |                 ^~~~
compat.c:652:17: note: include â€˜<stdlib.h>â€™ or provide a declaration of â€˜freeâ€™
compat.c:652:17: warning: incompatible implicit declaration of built-in function â€˜freeâ€™ [-Wbuiltin-declaration-mismatch]
compat.c:652:17: note: include â€˜<stdlib.h>â€™ or provide a declaration of â€˜freeâ€™
compat.c:652:27: warning: passing argument 1 of â€˜freeâ€™ discards â€˜constâ€™ qualifier from pointer target type [-Wdiscarded-qualifiers]
  652 |                 free(entry->name);
      |                      ~~~~~^~~~~~
compat.c:652:27: note: expected â€˜void *â€™ but argument is of type â€˜const char *â€™
compat.c:653:27: warning: passing argument 1 of â€˜freeâ€™ discards â€˜constâ€™ qualifier from pointer target type [-Wdiscarded-qualifiers]
  653 |                 free(entry->type);
      |                      ~~~~~^~~~~~
compat.c:653:27: note: expected â€˜void *â€™ but argument is of type â€˜const char *â€™
compat.c:654:27: warning: passing argument 1 of â€˜freeâ€™ discards â€˜constâ€™ qualifier from pointer target type [-Wdiscarded-qualifiers]
  654 |                 free(entry->domain);
      |                      ~~~~~^~~~~~~~
compat.c:654:27: note: expected â€˜void *â€™ but argument is of type â€˜const char *â€™
In file included from compat.c:48:
compat.c: In function â€˜DNSServiceBrowseâ€™:
warn.h:33:82: warning: ISO C does not support â€˜__FUNCTION__â€™ predefined identifier [-Wpedantic]
   33 | #define AVAHI_WARN_UNSUPPORTED do { avahi_warn_linkage(); avahi_warn_unsupported(__FUNCTION__); } while(0)
      |                                                                                  ^~~~~~~~~~~~
compat.c:719:9: note: in expansion of macro â€˜AVAHI_WARN_UNSUPPORTEDâ€™
  719 |         AVAHI_WARN_UNSUPPORTED;
      |         ^~~~~~~~~~~~~~~~~~~~~~
compat.c: In function â€˜DNSServiceResolveâ€™:
warn.h:33:82: warning: ISO C does not support â€˜__FUNCTION__â€™ predefined identifier [-Wpedantic]
   33 | #define AVAHI_WARN_UNSUPPORTED do { avahi_warn_linkage(); avahi_warn_unsupported(__FUNCTION__); } while(0)
      |                                                                                  ^~~~~~~~~~~~
compat.c:844:9: note: in expansion of macro â€˜AVAHI_WARN_UNSUPPORTEDâ€™
  844 |         AVAHI_WARN_UNSUPPORTED;
      |         ^~~~~~~~~~~~~~~~~~~~~~
compat.c: In function â€˜domain_browser_callbackâ€™:
compat.c:920:40: warning: incompatible implicit declaration of built-in function â€˜callocâ€™ [-Wbuiltin-declaration-mismatch]
  920 |                 domain_list_t *entry = calloc(1, sizeof(domain_list_t));
      |                                        ^~~~~~
compat.c:920:40: note: include â€˜<stdlib.h>â€™ or provide a declaration of â€˜callocâ€™
compat.c:964:17: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  964 |                 domain_list_t *tmp = entry->list_next;
      |                 ^~~~~~~~~~~~~
compat.c:965:17: warning: incompatible implicit declaration of built-in function â€˜freeâ€™ [-Wbuiltin-declaration-mismatch]
  965 |                 free(entry->domain);
      |                 ^~~~
compat.c:965:17: note: include â€˜<stdlib.h>â€™ or provide a declaration of â€˜freeâ€™
compat.c:965:27: warning: passing argument 1 of â€˜freeâ€™ discards â€˜constâ€™ qualifier from pointer target type [-Wdiscarded-qualifiers]
  965 |                 free(entry->domain);
      |                      ~~~~~^~~~~~~~
compat.c:965:27: note: expected â€˜void *â€™ but argument is of type â€˜const char *â€™
compat.c: In function â€˜DNSServiceEnumerateDomainsâ€™:
warn.h:33:82: warning: ISO C does not support â€˜__FUNCTION__â€™ predefined identifier [-Wpedantic]
   33 | #define AVAHI_WARN_UNSUPPORTED do { avahi_warn_linkage(); avahi_warn_unsupported(__FUNCTION__); } while(0)
      |                                                                                  ^~~~~~~~~~~~
compat.c:997:9: note: in expansion of macro â€˜AVAHI_WARN_UNSUPPORTEDâ€™
  997 |         AVAHI_WARN_UNSUPPORTED;
      |         ^~~~~~~~~~~~~~~~~~~~~~
compat.c: In function â€˜DNSServiceRegisterâ€™:
warn.h:33:82: warning: ISO C does not support â€˜__FUNCTION__â€™ predefined identifier [-Wpedantic]
   33 | #define AVAHI_WARN_UNSUPPORTED do { avahi_warn_linkage(); avahi_warn_unsupported(__FUNCTION__); } while(0)
      |                                                                                  ^~~~~~~~~~~~
compat.c:1253:9: note: in expansion of macro â€˜AVAHI_WARN_UNSUPPORTEDâ€™
 1253 |         AVAHI_WARN_UNSUPPORTED;
      |         ^~~~~~~~~~~~~~~~~~~~~~
compat.c: In function â€˜DNSServiceUpdateRecordâ€™:
warn.h:33:82: warning: ISO C does not support â€˜__FUNCTION__â€™ predefined identifier [-Wpedantic]
   33 | #define AVAHI_WARN_UNSUPPORTED do { avahi_warn_linkage(); avahi_warn_unsupported(__FUNCTION__); } while(0)
      |                                                                                  ^~~~~~~~~~~~
compat.c:1365:9: note: in expansion of macro â€˜AVAHI_WARN_UNSUPPORTEDâ€™
 1365 |         AVAHI_WARN_UNSUPPORTED;
      |         ^~~~~~~~~~~~~~~~~~~~~~
compat.c: In function â€˜query_resolver_callbackâ€™:
compat.c:1438:35: warning: incompatible implicit declaration of built-in function â€˜callocâ€™ [-Wbuiltin-declaration-mismatch]
 1438 |             query_list_t *entry = calloc(1, sizeof(query_list_t));
      |                                   ^~~~~~
compat.c:1438:35: note: include â€˜<stdlib.h>â€™ or provide a declaration of â€˜callocâ€™
compat.c:1483:13: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 1483 |             query_list_t *tmp = entry->list_next;
      |             ^~~~~~~~~~~~
compat.c:1484:13: warning: incompatible implicit declaration of built-in function â€˜freeâ€™ [-Wbuiltin-declaration-mismatch]
 1484 |             free(entry->name);
      |             ^~~~
compat.c:1484:13: note: include â€˜<stdlib.h>â€™ or provide a declaration of â€˜freeâ€™
compat.c:1484:23: warning: passing argument 1 of â€˜freeâ€™ discards â€˜constâ€™ qualifier from pointer target type [-Wdiscarded-qualifiers]
 1484 |             free(entry->name);
      |                  ~~~~~^~~~~~
compat.c:1484:23: note: expected â€˜void *â€™ but argument is of type â€˜const char *â€™
compat.c: In function â€˜DNSServiceQueryRecordâ€™:
warn.h:33:82: warning: ISO C does not support â€˜__FUNCTION__â€™ predefined identifier [-Wpedantic]
   33 | #define AVAHI_WARN_UNSUPPORTED do { avahi_warn_linkage(); avahi_warn_unsupported(__FUNCTION__); } while(0)
      |                                                                                  ^~~~~~~~~~~~
compat.c:1519:9: note: in expansion of macro â€˜AVAHI_WARN_UNSUPPORTEDâ€™
 1519 |         AVAHI_WARN_UNSUPPORTED;
      |         ^~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: Leaving directory '/builddir/build/BUILD/avahi-0.8/avahi-compat-libdns_sd'
make[2]: *** [Makefile:923: null_test-compat.o] Error 1
make[1]: *** [Makefile:833: all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/avahi-0.8'
make: *** [Makefile:743: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.LtDgfT (%build)
```

**Comment by evverx** [comment]
I think it can be closed. In its current form it can't be merged because it fails to build and comes with no tests. If anyone is interested in picking it up it should be possible to open a new PR.

**Pull request closed without merging**
