### PR TITLE
Support GTK+ 4.0

### PR DESCRIPTION
**Pull request by murraycu**
These commits first avoid some deprecated API, then add a GTK4 version of avahi-ui, and then make some GTK4-specific changes.

I have not tested this at all and there doesn't seem to be any example/demo code for avahi-ui in the avahi repository itself.

### CODE REVIEW

**Comment by evverx** [comment]
I rebased this PR on top of the master branch of my fork to trigger the CI. Looks like it fails to build
```
avahi-ui/Makefile.am:88: but option 'subdir-objects' is disabled
man/Makefile.am:59: error: HAVE_GTK2OR3 does not appear in AM_CONDITIONAL
man/Makefile.am:138: error: HAVE_GTK2OR3 does not appear in AM_CONDITIONAL
Error: Process completed with exit code 1.
```

**Comment by evverx** [comment]
It's being discussed in https://github.com/lathiat/avahi/issues/516 but nobody apart from NixOS and Debian has shown up yet.

**Comment by Neustradamus** [comment]
Good links to read:
- https://docs.gtk.org/gtk4/migrating-4to5.html

**Comment by Neustradamus** [comment]
A good link to read:
- https://docs.gtk.org/gtk4/migrating-4to5.html

**Comment by evverx** [comment]
The CI fails so I think this PR can be closed.

To judge from https://github.com/avahi/avahi/issues/516 the avahi-ui part can safely be dropped.

**Comment by murraycu** [comment]
(responding to someone emailing me asking me to rebase this.) 

I won't be spending time updating this. I wrote this 7 years ago. Please feel free to do whatever you like with it.

**Pull request closed without merging**
