### PR TITLE
Add interface attribute for Avahi service files

### PR DESCRIPTION
**Pull request by BrianClaggett**
Add interface attribute for Avahi service files. If present,
the service will publish only on the specified interface. If
not present the default behavior of publishing on all interfaces is unchanged.
The value for this attribute is the system ifname. If the interface is invalid,
the service is not published and an error is logged.
Allows a system to control what services are available if connected to multiple networks and vlans.

### CODE REVIEW

**Comment by pboyd04** [comment]
Any update on when this might be included?

**Comment by BrianClaggett** [comment]
Fixed the merge conflicts. @lathiat - old change, any chance of being merged to main branch?

**Review by pemensik — CHANGES_REQUESTED** [review]
I would like to request removing your email address from the first line. A summary of commit belongs there. If you want your contact there, just use ``Author: <someone@example.org>`` or ``Sign-off-by: Me <me@example.org>``.

**Review by BrianClaggett — COMMENTED** [review]
I don't think there is a need for an author line at all in the commit text. Please let me know if I am wrong.

**Comment by pemensik** [comment]
I would suggest using ``git pull --rebase`` to move your change on top of current master branch in this repository. Use ``git commit --amend`` to adjust description of previous commit. Use ``git rebase -i origin/master``, then you can edit also previous commits by changing pick to edit, or at least reword. Then ``git push -f brian`` to your branch.

The issue I have here is ``git log --oneline`` would *not* show useful message for this change. Suggested commit message:

```
Add interface attribute for Avahi service files

If present, the service will publish only on the specified interface. If
not present the default behavior of publishing on all interfaces is unchanged.
The value for this attribute is the system ifname. If the interface is invalid,
the service is not published and an error is logged.
Allows a system to control what services are available if connected to multiple networks and vlans.
```

Yes, would would still be author of this commit visible in log. There is no need to have your email mentioned in commit message.

**Comment by evverx** [comment]
Looks like it segfaults
```sh
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b59d1d in __strlen_avx2 () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install dbus-libs-1.14.10-1.fc38.x86_64 expat-2.5.0-2.fc38.x86_64 glibc-2.37-12.fc38.x86_64 libcap-2.48-6.fc38.x86_64 libdaemon-0.14-25.fc38.x86_64 libgcc-13.2.1-4.fc38.x86_64 libzstd-1.5.5-1.fc38.x86_64 lz4-libs-1.9.4-2.fc38.x86_64 systemd-libs-253.10-1.fc38.x86_64 xz-libs-5.4.1-1.fc38.x86_64
(gdb) bt
#0  0x00007ffff7b59d1d in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007ffff7b28308 in if_nametoindex () from /lib64/libc.so.6
#2  0x0000000000479b91 in if_nametoindex ()
#3  0x0000000000510bc2 in xml_end (data=0x7ffff5b01220, el=<optimized out>) at static-services.c:633
#4  0x00007ffff7d5f93a in doContent () from /lib64/libexpat.so.1
#5  0x00007ffff7d5c5ba in doProlog () from /lib64/libexpat.so.1
#6  0x00007ffff7d5ead1 in prologProcessor () from /lib64/libexpat.so.1
#7  0x00007ffff7d62af0 in XML_ParseBuffer () from /lib64/libexpat.so.1
#8  0x000000000050b16f in static_service_group_load (g=0x607000000560) at static-services.c:861
#9  0x000000000050a0ff in load_file (n=<optimized out>) at static-services.c:895
#10 static_service_load (in_chroot=<optimized out>) at static-services.c:952
#11 0x0000000000501ad1 in run_server (c=<optimized out>) at main.c:1247
#12 0x00000000004fa00c in main (argc=<optimized out>, argv=<optimized out>) at main.c:1693
```

**Comment by evverx** [comment]
I think it can be closed. It segfaults, comes with no tests and there has been no response. If anyone is interested in picking it up just let me know and I'll reopen it.

**Comment by pboyd04** [comment]
Sorry those of us on this are not on the product using this anymore. I'm attempting to get someone one the product to look into why this segfaults on the latest code.

**Pull request closed without merging**
