### PR TITLE
Fix entry group probing when new interface is announced.

### PR DESCRIPTION
**Pull request by hsebert**
When an interface is withdrawn and added again during server start-up or service registration, the corresponding entry groups do not leave probing state. This leads to either the server not starting up at all (not leaving the AVAHI_REGISTERING state) or the service not being registered (corresponding entry group not leaving the AVAHI_ENTRY_GROUP_REGISTERING state). This is fixed by not further increasing the corresponding probing counters when an interface is (re-)announced.

### CODE REVIEW

**Comment by evverx** [comment]
I wonder if this issue is reproducible with the master branch (with https://github.com/lathiat/avahi/commit/cb15988c4c676410549ef1d04487107cd484b353 included)?

**Comment by evverx** [comment]
I'll go ahead and close it. If it's still reproducible with the master branch just let me know and I reopen it.

**Comment by phvega** [comment]
I don't know if cb15988c4c676410549ef1d04487107cd484b353 worked for OP, but in my case this does not seem to fix the problem. However, applying this PR's patch looks like it **did** fix it.

Could you maybe consider revisiting this issue?

Thank you!.

**Comment by evverx** [comment]
Could you run avahi with the `--debug` option enabled and paste the logs? It should help to figure out what's going on.

**Comment by phvega** [comment]
Sure, looks like it begins to load the service ("Loading service file /etc/avahi/services/http.service.") but there is no result log (e.g. "... successfully established"):

```
Feb 24 04:00:35 avahi-daemon[599]: Found user 'nobody' (UID 65534) and group 'nogroup' (GID 65534).
Feb 24 04:00:35 avahi-daemon[599]: Successfully dropped root privileges.
Feb 24 04:00:35 avahi-daemon[599]: avahi-daemon 0.7 starting up.
Feb 24 04:00:35 avahi-daemon[599]: WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Feb 24 04:00:35 avahi-daemon[599]: Loading service file /etc/avahi/services/http.service.
Feb 24 04:00:35 avahi-daemon[599]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.219.
Feb 24 04:00:35 avahi-daemon[599]: New relevant interface eth0.IPv4 for mDNS.
Feb 24 04:00:35 avahi-daemon[599]: Network interface enumeration completed.
Feb 24 04:00:35 avahi-daemon[599]: Registering new address record for 192.168.0.219 on eth0.IPv4.
Feb 24 04:00:35 avahi-daemon[599]: Server startup complete. Host name is rc2-01007F86.local. Local service cookie is 2523018912.
Feb 24 04:00:36 avahi-daemon[599]: Service "a4ed43107f86" (/etc/avahi/services/http.service) successfully established.
Feb 24 04:00:57 avahi-daemon[599]: Files changed, reloading.
Feb 24 04:00:57 avahi-daemon[599]: Service group file /etc/avahi/services/http.service vanished, removing services.
Feb 24 04:00:57 avahi-daemon[599]: No service file found in /etc/avahi/services.
Feb 24 04:00:57 avahi-daemon[599]: Interface eth0.IPv4 no longer relevant for mDNS.
Feb 24 04:00:57 avahi-daemon[599]: Leaving mDNS multicast group on interface eth0.IPv4 with address 192.168.0.219.
Feb 24 04:00:57 avahi-daemon[599]: Withdrawing address record for 192.168.0.219 on eth0.
Feb 24 04:00:57 avahi-daemon[599]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.220.
Feb 24 04:00:57 avahi-daemon[599]: New relevant interface eth0.IPv4 for mDNS.
Feb 24 04:00:57 avahi-daemon[599]: Registering new address record for 192.168.0.220 on eth0.IPv4.
Feb 24 04:01:14 avahi-daemon[599]: Files changed, reloading.
Feb 24 04:01:14 avahi-daemon[599]: Loading service file /etc/avahi/services/http.service.
Feb 24 04:01:14 avahi-daemon[599]: Withdrawing address record for 192.168.0.220 on eth0.
Feb 24 04:01:14 avahi-daemon[599]: Leaving mDNS multicast group on interface eth0.IPv4 with address 192.168.0.220.
Feb 24 04:01:14 avahi-daemon[599]: Interface eth0.IPv4 no longer relevant for mDNS.
Feb 24 04:01:14 avahi-daemon[599]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.219.
Feb 24 04:01:14 avahi-daemon[599]: New relevant interface eth0.IPv4 for mDNS.
Feb 24 04:01:14 avahi-daemon[599]: Registering new address record for 192.168.0.219 on eth0.IPv4.
```

**Comment by evverx** [comment]
Got it. As far as I can tell https://github.com/avahi/avahi/commit/cb15988c4c676410549ef1d04487107cd484b353 was applied on top of `0.7` released in 2017. Could you try with `0.9-rc1` (or the master branch)? Could you also paste the "avahi-daemon.conf" file and the http service file just in case?

**Comment by evverx** [comment]
Just to make sure I wonder if https://github.com/avahi/avahi/commit/cb15988c4c676410549ef1d04487107cd484b353 was applied on top of `0.7`?

The first avahi version where that commit is included is `0.9-rc1`.

**Comment by phvega** [comment]
Yes, sorry I did not explain myself, I backported cb15988 on top of `0.7` and it did not fix the problem.

I was planning on testing upgrading to `0.9-rc1` before answering when I could in the following days.

**Comment by phvega** [comment]
Seems like I must have incorrectly tested the cb15988 backport because after testing `0.9-rc1`, which fixed the problem, I retried backporting the commit to `0.7` and it also fixed the problem..

Just a quick question before closing this, when testing I noticed a slight difference on the logs for `0.7` and `0.9-rc1`:

`0.7`:
```
Feb 24 21:11:17 avahi-daemon[660]: Files changed, reloading.
Feb 24 21:11:17 avahi-daemon[660]: Loading service file /etc/avahi/services/http.service.
Feb 24 21:11:17 avahi-daemon[660]: Withdrawing address record for 192.168.1.219 on eth0.
Feb 24 21:11:17 avahi-daemon[660]: Leaving mDNS multicast group on interface eth0.IPv4 with address 192.168.1.219.
Feb 24 21:11:17 avahi-daemon[660]: Interface eth0.IPv4 no longer relevant for mDNS.
Feb 24 21:11:17 avahi-daemon[660]: Service "a4ed43107f86" (/etc/avahi/services/http.service) successfully established.
Feb 24 21:11:17 avahi-daemon[660]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.219.
Feb 24 21:11:17 avahi-daemon[660]: New relevant interface eth0.IPv4 for mDNS.
Feb 24 21:11:17 avahi-daemon[660]: Registering new address record for 192.168.0.219 on eth0.IPv4.
```

And `0.9-rc1`:
```
Feb 24 21:09:13 avahi-daemon[603]: Files changed, reloading.
Feb 24 21:09:13 avahi-daemon[603]: Loading service file /etc/avahi/services/http.service.
Feb 24 21:09:13 avahi-daemon[603]: Withdrawing address record for 192.168.1.219 on eth0.
Feb 24 21:09:13 avahi-daemon[603]: Leaving mDNS multicast group on interface eth0.IPv4 with address 192.168.1.219.
Feb 24 21:09:13 avahi-daemon[603]: Interface eth0.IPv4 no longer relevant for mDNS.
Feb 24 21:09:13 avahi-daemon[603]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.0.219.
Feb 24 21:09:13 avahi-daemon[603]: New relevant interface eth0.IPv4 for mDNS.
Feb 24 21:09:13 avahi-daemon[603]: Registering new address record for 192.168.0.219 on eth0.IPv4.
Feb 24 21:09:14 avahi-daemon[603]: Service "a4ed43107f86" (/etc/avahi/services/http.service) successfully established.
```

In `0.9-rc1` the service is established after the interface update is done, while in `0.7` it happens in the middle of it, should I care for this?

**Comment by evverx** [comment]
I think as long as services are published it doesn't matter much (after all it could be that logs are interleaved when they are written to the journal). I think it would be better to switch to the latest version of avahi because quite a few other bugs have been fixed since then.

**Pull request closed without merging**
